
name : Deploy

on :
  push:
    branches : [ main ]

env:
  CARGO_TERM_COLOR: always

jobs :
  deploy :
    runs-on : ubuntu-latest
    steps :
      - name: Build server and web on remote
        uses: appleboy/ssh-action@alpha
        with:
          host: ${{ secrets.PRIVATE_SERVER_HOST }}
          username: ${{ secrets.PRIVATE_SERVER_USER }}
          key: ${{ secrets.PRIVATE_SERVER_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            git clone https://github.com/Wandalen/game_chess.git
            cd game_chess
            git checkout main
            git pull
            ~/.cargo/bin/cargo build --bin chess_server --release
            ~/.cargo/bin/cargo make web_build_release
            cp -R target/web/* ${{ secrets.PRIVATE_SERVER_PATH }}
